// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright 2025-2026 TautCony

namespace ISTgenerAtor;

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class PatchUtilsGenerator : IIncrementalGenerator
{
    // 明文常量 - 直接在这里修改即可
    private const string PatcherName = "BimmerSpace";
    private const string ConfigFormat = "Powered by {0}";
    private const string SourceUrl = "ISTA-Patcher";

    public void Initialize(IncrementalGeneratorInitializationContext incrementalContext)
    {
        var classExistsProvider = incrementalContext.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { Identifier.Text: "PatchUtils" },
                transform: static (context, t) =>
                    context.SemanticModel.GetDeclaredSymbol(context.Node, t) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null)
            .Collect();

        incrementalContext.RegisterSourceOutput(classExistsProvider, (context, classSymbols) =>
        {
            if (!classSymbols.Any())
            {
                return;
            }

            context.AddSource(
                "ISTAlter.Core.PatchUtils.g.cs",
                SourceText.From(GenerateCode(), Encoding.UTF8));
        });
    }

    private static string GenerateCode()
    {
        return $@"// <auto-generated/>
namespace ISTAlter.Core;

using System.Text;
using dnlib.DotNet;

public static partial class PatchUtils
{{
    // Patcher name (明文常量)
    public const string PatcherName = ""{PatcherName}"";
    
    // Config: AssemblyDescription content
    public static byte[] Config => Encoding.UTF8.GetBytes(string.Format(""{ConfigFormat}"", PatcherName));
    
    // Source: GitHub repository URL
    public static byte[] Source => Encoding.UTF8.GetBytes(""{SourceUrl}"");

    public static void SetPatchedMark(ModuleDefMD module)
    {{
        PatchUtils.SetPatchedMarkInner(module);
        PatchUtils.ValidatePatchResult(module);
    }}
}}
";
    }
}
