// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright 2026 TautCony

namespace ISTgenerAtor;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class XsdModelGenerator : IIncrementalGenerator
{
    private static readonly XNamespace Xs = "http://www.w3.org/2001/XMLSchema";
    private static readonly XNamespace CodeGen = "urn:ista-patcher:xsd-codegen";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var schemas = context.AdditionalTextsProvider
            .Where(static file => Path.GetExtension(file.Path).Equals(".xsd", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, token) => new XsdInput(file.Path, file.GetText(token)?.ToString() ?? string.Empty));

        context.RegisterSourceOutput(schemas, static (sourceContext, schema) =>
        {
            if (string.IsNullOrWhiteSpace(schema.Content))
            {
                return;
            }

            var generated = Generate(schema);
            if (generated.Length == 0)
            {
                return;
            }

            var hintName = Path.GetFileNameWithoutExtension(schema.Path) + ".XsdModels.g.cs";
            sourceContext.AddSource(hintName, SourceText.From(generated, Encoding.UTF8));
        });
    }

    private static string Generate(XsdInput input)
    {
        var document = XDocument.Parse(input.Content);
        var schema = document.Root;
        if (schema is null)
        {
            return string.Empty;
        }

        var targetNamespace = schema.Attribute("targetNamespace")?.Value ?? string.Empty;
        var modelNamespace = GetModelNamespace(input.Path);
        if (modelNamespace is null)
        {
            return string.Empty;
        }

        var classOptions = schema.Descendants(CodeGen + "class")
            .Select(ParseClassOptions)
            .Where(static option => !string.IsNullOrWhiteSpace(option.XsdType))
            .ToDictionary(static option => option.Name, StringComparer.Ordinal);

        var rootElements = schema.Elements(Xs + "element")
            .Where(static element => element.Attribute("type") is not null)
            .ToDictionary(
                static element => RemovePrefix(element.Attribute("type")?.Value ?? string.Empty),
                static element => new RootElement(
                    element.Attribute("name")?.Value ?? string.Empty,
                    string.Equals(element.Attribute("nillable")?.Value, "true", StringComparison.OrdinalIgnoreCase)));

        var simpleTypes = schema.Elements(Xs + "simpleType")
            .Select(ParseSimpleType)
            .Where(static type => type.Values.Count > 0)
            .ToDictionary(static type => type.Name, StringComparer.Ordinal);

        var complexTypes = schema.Elements(Xs + "complexType")
            .Select(element => ParseComplexType(element, rootElements, simpleTypes))
            .ToList();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {modelNamespace};");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Runtime.Serialization;");
        builder.AppendLine("using System.Xml.Schema;");
        builder.AppendLine("using System.Xml.Serialization;");
        foreach (var usingNamespace in classOptions.Values
            .Select(static option => option.UsingNamespace)
            .Where(static usingNamespace => !string.IsNullOrWhiteSpace(usingNamespace))
            .Distinct(StringComparer.Ordinal))
        {
            builder.AppendLine($"using {usingNamespace};");
        }

        builder.AppendLine();

        foreach (var simpleType in simpleTypes.Values)
        {
            AppendEnum(builder, simpleType, targetNamespace);
        }

        foreach (var complexType in complexTypes)
        {
            classOptions.TryGetValue(complexType.Name, out var classOption);
            AppendClass(builder, complexType, targetNamespace, classOption);
        }

        return builder.ToString();
    }

    private static string? GetModelNamespace(string path)
    {
        var normalized = path.Replace('\\', '/');
        var parts = normalized.Split('/');
        var schemaIndex = Array.LastIndexOf(parts, "Schemas");
        if (schemaIndex <= 0 || schemaIndex >= parts.Length - 1)
        {
            return null;
        }

        var projectName = parts[schemaIndex - 1];
        var namespaceParts = parts.Skip(schemaIndex + 1).Take(parts.Length - schemaIndex - 2).ToArray();
        if (namespaceParts.Length == 0)
        {
            return projectName + ".Models";
        }

        return projectName + ".Models." + string.Join(".", namespaceParts);
    }

    private static SimpleType ParseSimpleType(XElement element)
    {
        var name = element.Attribute("name")?.Value ?? string.Empty;
        var values = element.Element(Xs + "restriction")?
            .Elements(Xs + "enumeration")
            .Select(static value => value.Attribute("value")?.Value ?? string.Empty)
            .Where(static value => value.Length > 0)
            .ToArray() ?? [];
        return new SimpleType(name, values);
    }

    private static ComplexType ParseComplexType(
        XElement element,
        IReadOnlyDictionary<string, RootElement> rootElements,
        IReadOnlyDictionary<string, SimpleType> simpleTypes)
    {
        var name = element.Attribute("name")?.Value ?? string.Empty;
        rootElements.TryGetValue(name, out var rootElement);

        var properties = new List<Property>();
        var order = 0;
        foreach (var child in element.Element(Xs + "sequence")?.Elements(Xs + "element") ?? [])
        {
            properties.Add(ParseProperty(child, PropertyKind.Element, order++, simpleTypes));
        }

        foreach (var attribute in element.Elements(Xs + "attribute"))
        {
            properties.Add(ParseProperty(attribute, PropertyKind.Attribute, null, simpleTypes));
            if (ShouldGenerateSpecified(attribute, simpleTypes))
            {
                properties.Add(new Property(
                    attribute.Attribute("name")?.Value + "Specified",
                    "bool",
                    "bool",
                    PropertyKind.Specified,
                    null,
                    null,
                    null,
                    false,
                    false,
                    null,
                    false));
            }
        }

        return new ComplexType(name, rootElement, properties);
    }

    private static ClassOptions ParseClassOptions(XElement element)
    {
        return new ClassOptions(
            element.Attribute("xsdType")?.Value ?? element.Attribute("name")?.Value ?? string.Empty,
            element.Attribute("clrBaseTypes")?.Value ?? element.Attribute("base")?.Value,
            element.Attribute("clrUsingNamespace")?.Value ?? element.Attribute("using")?.Value);
    }

    private static Property ParseProperty(
        XElement element,
        PropertyKind kind,
        int? order,
        IReadOnlyDictionary<string, SimpleType> simpleTypes)
    {
        var xmlName = element.Attribute("name")?.Value ?? string.Empty;
        var xsdType = RemovePrefix(element.Attribute("type")?.Value ?? "xs:string");
        var isList = string.Equals(element.Attribute("maxOccurs")?.Value, "unbounded", StringComparison.OrdinalIgnoreCase);
        var isNullable = string.Equals(element.Attribute("nillable")?.Value, "true", StringComparison.OrdinalIgnoreCase);
        var dataType = GetXmlDataType(element.Attribute("type")?.Value ?? string.Empty);
        var form = element.Attribute("form")?.Value;
        var defaultValue = element.Attribute("default")?.Value;
        var clrType = GetClrType(xsdType, simpleTypes);
        var propertyType = isList ? $"List<{clrType}>" : GetPropertyType(clrType, xsdType, kind, isNullable, element, simpleTypes);

        return new Property(
            xmlName,
            propertyType,
            clrType,
            kind,
            xmlName,
            order,
            dataType,
            isNullable,
            isList,
            form,
            defaultValue is not null);
    }

    private static bool ShouldGenerateSpecified(XElement attribute, IReadOnlyDictionary<string, SimpleType> simpleTypes)
    {
        var type = RemovePrefix(attribute.Attribute("type")?.Value ?? string.Empty);
        var use = attribute.Attribute("use")?.Value;
        return use != "required" && IsClrValueType(type, GetClrType(type, simpleTypes), simpleTypes);
    }

    private static string GetClrType(string xsdType, IReadOnlyDictionary<string, SimpleType> simpleTypes)
    {
        return xsdType switch
        {
            "string" or "anyURI" or "integer" or "language" => "string",
            "dateTime" => "DateTime",
            "boolean" => "bool",
            "base64Binary" => "byte[]",
            _ when simpleTypes.ContainsKey(xsdType) => xsdType,
            _ => xsdType,
        };
    }

    private static string GetPropertyType(
        string clrType,
        string xsdType,
        PropertyKind kind,
        bool isNullable,
        XElement element,
        IReadOnlyDictionary<string, SimpleType> simpleTypes)
    {
        var isRequired = IsRequired(element, kind);
        if (!IsClrValueType(xsdType, clrType, simpleTypes))
        {
            return isRequired && !isNullable ? clrType : clrType + "?";
        }

        if (kind == PropertyKind.Attribute)
        {
            return clrType;
        }

        return isRequired && !isNullable ? clrType : clrType + "?";
    }

    private static bool IsClrValueType(string xsdType, string clrType, IReadOnlyDictionary<string, SimpleType> simpleTypes)
    {
        return xsdType is "dateTime" or "boolean" || simpleTypes.ContainsKey(clrType);
    }

    private static bool IsRequired(XElement element, PropertyKind kind)
    {
        if (kind == PropertyKind.Attribute)
        {
            return element.Attribute("use")?.Value == "required";
        }

        return element.Attribute("minOccurs")?.Value != "0";
    }

    private static string? GetXmlDataType(string type)
    {
        return RemovePrefix(type) switch
        {
            "anyURI" => "anyURI",
            "integer" => "integer",
            "language" => "language",
            "base64Binary" => "base64Binary",
            _ => null,
        };
    }

    private static string RemovePrefix(string value)
    {
        var index = value.IndexOf(':');
        return index < 0 ? value : value.Substring(index + 1);
    }

    private static void AppendEnum(StringBuilder builder, SimpleType simpleType, string targetNamespace)
    {
        builder.AppendLine("[Serializable]");
        builder.AppendLine($"[XmlType(Namespace = \"{Escape(targetNamespace)}\")]");
        builder.AppendLine($"public enum {simpleType.Name}");
        builder.AppendLine("{");
        foreach (var value in simpleType.Values)
        {
            builder.AppendLine($"    {value},");
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendClass(StringBuilder builder, ComplexType complexType, string targetNamespace, ClassOptions? classOptions)
    {
        builder.AppendLine("[Serializable]");
        builder.AppendLine($"[XmlType(Namespace = \"{Escape(targetNamespace)}\")]");
        if (complexType.RootElement is not null)
        {
            builder.AppendLine($"[XmlRoot(Namespace = \"{Escape(targetNamespace)}\", IsNullable = {FormatBool(complexType.RootElement.IsNullable)})]");
        }

        builder.AppendLine($"[DataContract(Name = \"{complexType.Name}\", Namespace = \"{Escape(targetNamespace)}\")]");
        builder.Append($"public partial class {complexType.Name}");
        var baseType = classOptions?.BaseType;
        if (!string.IsNullOrWhiteSpace(baseType))
        {
            builder.Append($" : {baseType}");
        }

        builder.AppendLine();
        builder.AppendLine("{");
        foreach (var property in complexType.Properties)
        {
            AppendProperty(builder, property);
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendProperty(StringBuilder builder, Property property)
    {
        builder.AppendLine();
        switch (property.Kind)
        {
            case PropertyKind.Element:
                AppendXmlElementAttribute(builder, property);
                builder.AppendLine("    [DataMember]");
                builder.AppendLine($"    public {property.Type} {property.Name} {{ get; set; }}{GetInitializer(property)}");
                break;
            case PropertyKind.Attribute:
                AppendXmlAttributeAttribute(builder, property);
                builder.AppendLine("    [DataMember]");
                builder.AppendLine($"    public {property.Type} {property.Name} {{ get; set; }}{GetInitializer(property)}");
                break;
            case PropertyKind.Specified:
                builder.AppendLine("    [XmlIgnore]");
                builder.AppendLine("    [DataMember]");
                builder.AppendLine($"    public bool {property.Name} {{ get; set; }}");
                break;
        }
    }

    private static void AppendXmlElementAttribute(StringBuilder builder, Property property)
    {
        var arguments = new List<string>();
        if (property.XmlName != property.Name || property.IsList)
        {
            arguments.Add($"\"{Escape(property.XmlName ?? property.Name)}\"");
        }

        if (property.Form == "unqualified")
        {
            arguments.Add("Form = XmlSchemaForm.Unqualified");
        }

        if (property.DataType is not null)
        {
            arguments.Add($"DataType = \"{property.DataType}\"");
        }

        if (property.IsNullable)
        {
            arguments.Add("IsNullable = true");
        }

        if (property.Order is not null)
        {
            arguments.Add("Order = " + property.Order.Value.ToString(CultureInfo.InvariantCulture));
        }

        builder.AppendLine($"    [XmlElement({string.Join(", ", arguments)})]");
    }

    private static void AppendXmlAttributeAttribute(StringBuilder builder, Property property)
    {
        if (property.DataType is null)
        {
            builder.AppendLine("    [XmlAttribute]");
            return;
        }

        builder.AppendLine($"    [XmlAttribute(DataType = \"{property.DataType}\")]");
    }

    private static string GetInitializer(Property property)
    {
        if (property.HasDefaultValue && property.Type == property.ClrType && property.ClrType != "string")
        {
            return " = " + property.ClrType + ".offline;";
        }

        if (property.IsList)
        {
            return " = new List<" + property.ClrType + ">();";
        }

        if (property.Type == "string")
        {
            return " = string.Empty;";
        }

        if (!property.Type.EndsWith("?", StringComparison.Ordinal)
            && property.ClrType != "DateTime"
            && property.ClrType != "bool"
            && property.Kind is PropertyKind.Element)
        {
            return " = new " + property.ClrType + "();";
        }

        return string.Empty;
    }

    private static string FormatBool(bool value)
    {
        return value ? "true" : "false";
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", @"\\").Replace("\"", "\\\"");
    }

    private readonly struct XsdInput(string path, string content)
    {
        public string Path { get; } = path;

        public string Content { get; } = content;
    }

    private sealed class RootElement(string name, bool isNullable)
    {
        public string Name { get; } = name;

        public bool IsNullable { get; } = isNullable;
    }

    private sealed class SimpleType(string name, IReadOnlyList<string> values)
    {
        public string Name { get; } = name;

        public IReadOnlyList<string> Values { get; } = values;
    }

    private sealed class ComplexType(string name, RootElement? rootElement, IReadOnlyList<Property> properties)
    {
        public string Name { get; } = name;

        public RootElement? RootElement { get; } = rootElement;

        public IReadOnlyList<Property> Properties { get; } = properties;
    }

    private sealed class ClassOptions(string xsdType, string? baseType, string? usingNamespace)
    {
        public string XsdType { get; } = xsdType;

        public string Name { get; } = xsdType;

        public string? BaseType { get; } = baseType;

        public string? UsingNamespace { get; } = usingNamespace;
    }

    private sealed class Property(
        string name,
        string type,
        string clrType,
        PropertyKind kind,
        string? xmlName,
        int? order,
        string? dataType,
        bool isNullable,
        bool isList,
        string? form,
        bool hasDefaultValue)
    {
        public string Name { get; } = name;

        public string Type { get; } = type;

        public string ClrType { get; } = clrType;

        public PropertyKind Kind { get; } = kind;

        public string? XmlName { get; } = xmlName;

        public int? Order { get; } = order;

        public string? DataType { get; } = dataType;

        public bool IsNullable { get; } = isNullable;

        public bool IsList { get; } = isList;

        public string? Form { get; } = form;

        public bool HasDefaultValue { get; } = hasDefaultValue;
    }

    private enum PropertyKind
    {
        Element,
        Attribute,
        Specified,
    }
}
